# Generated by Django 4.1.7 on 2023-05-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('material', models.CharField(max_length=50)),
                ('fabric_finish', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('characteristic', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='media/')),
            ],
            options={
                'verbose_name': 'scarf',
            },
        ),
        migrations.CreateModel(
            name='Product2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('color', models.CharField(max_length=60)),
                ('material', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Length_from_shoulder_to_feet', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='media/')),
            ],
            options={
                'verbose_name': 'Prayer dress',
            },
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=100, null=True)),
                ('Phone', models.CharField(max_length=100, null=True)),
                ('Address', models.CharField(max_length=100, null=True)),
                ('Password', models.CharField(max_length=100, null=True)),
                ('Username', models.CharField(max_length=100, null=True)),
                ('Image', models.ImageField(null=True, upload_to='media/')),
            ],
        ),
    ]
