# Generated by Django 4.1.2 on 2023-05-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product1',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
